# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogDB:
   image: postgres
   environment:
      POSTGRES_PASSWORD: abc@123+-
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDB
   ports :
    - 5432:5432

  basketDB:
   image: postgres
   environment:
      POSTGRES_PASSWORD: abc@123+-
      POSTGRES_USER: postgres
      POSTGRES_DB: BasketDB
   ports :
    - 5433:5432

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/CatalogAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ConnectionStrings__Databases=Server=catalogDB;port=5432;Database=CatalogDB;User Id=postgres;Password=abc@123+-;Include Error Detail=true
    ports :
      - 6000:8080
      - 6060:8081
    

volumes:
  postgress_catalog:
  postgress_basket:
