global using MediatR;
global using BuildingBlocks.CQRS;
global using Carter;
global using Mapster;
global using Marten;
global using CatalogAPI.Exceptions;
global using FluentValidation;
global using BuildingBlocks.Behaviours;
global using BuildingBlocks.Exceptions;