FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/Services/Discount/DiscountGRPC/DiscountGRPC.csproj", "src/Services/Discount/DiscountGRPC/"]
RUN dotnet restore "src/Services/Discount/DiscountGRPC/DiscountGRPC.csproj"
COPY . .
WORKDIR "/src/src/Services/Discount/DiscountGRPC"
RUN dotnet build "DiscountGRPC.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "DiscountGRPC.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DiscountGRPC.dll"]
